### ISSUE TITLE
JADE THE TERRIBLE/ THAT DOT

### ISSUE THREAD

**Issue by RobertoAF** [UniStudentCollective-TurtleRunners/UniversalStudentCollective#65]
Hi guys,

Jade is terrible and has been causing countless hours of conversion hell.
It's causing us to lose countless hours of valuable coding time.

I'm proposing that we simply use HTML in our Jade files by following this Stack Overflow article:
![screen shot 2017-04-03 at 1 35 10 pm](https://cloud.githubusercontent.com/assets/13029161/24630699/87c18c52-1872-11e7-9141-a6f1e5558003.png)

I did this with our code, and it worked! Check it out. All you have to do is add that dot at the end of the second line of jade.
![screen shot 2017-04-03 at 1 33 23 pm](https://cloud.githubusercontent.com/assets/13029161/24630762/c2101586-1872-11e7-9291-312ed35b14d7.png)

Our site still works:
![screen shot 2017-04-03 at 1 40 08 pm](https://cloud.githubusercontent.com/assets/13029161/24630871/1f6553fe-1873-11e7-80a7-217faf656733.png)

**Comment by ideheer** [comment]
Hi Roberto,
  We were working on the app today and discovered that rendering the main page as HTML is causing problems with the way the routes function. For instance, the /main route contains a title: Main which is not being rendered because the <head> in the main.jade file is overwriting it.  Just removing this is not resolving the issue.  I think we need to render the main page as a jade file in order to implement other things as well. Do you think you can take an HTML file and plug it into the jade converter to make it work?

**Comment by RobertoAF** [comment]
If there is no alternative, then I think you're right in suggesting that it's best to go with what works. 
And yes, we can continue to plug HTML into the Jade converter.
Let me just take a moment before the next round of front-end adjustments...
![image](https://cloud.githubusercontent.com/assets/13029161/24825992/c13326c8-1be0-11e7-9a28-a66c86b5e3a1.png)
